### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Viscmad** [steadyequipment/node-firestore-backup#14]
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/src/node/extension_binary'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/src/grpc_extension.js:37:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/src/client.js:38:12)

**Comment by Viscmad** [comment]
Reinstallation fixed the issue.

**Comment by yoiang** [comment]
This sounds like an issue with `grpc`, do you feel otherwise?

**Comment by Viscmad** [comment]
Something got left out while installation @ 1st time. Reinstall fixed it.
